---

name: Release

on:
  release:
    types:
      - created

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-20.04
    name: packer-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH private Key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
          echo "${{ secrets.PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts

      - name: Install packer and ansible
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add - && \
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" && \
          sudo apt-get update && sudo apt-get install -y packer ansible

      # init plugins
      - name: Init Plugins
        run: packer init packer/

      # build artifact
      - name: Build Artifact
        run: packer build -color=false -on-error=abort packer/
        env:
          PACKER_LOG: 1
          GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          PACKER_LOG_PATH: /tmp/packer.log
          PKR_VAR_release: ${{ github.event.release.tag_name }}


      - name: Salva logs do Packer
        uses: actions/upload-artifact@v2
        with:
          name: packer-logs
          path: /tmp/packer.log
